version: "3.9"

services:
  frontend:
    build:
      context: ./docker/frontend/nginx
    ports:
      - "9005:9005"
      - "9006:80"
    volumes:
      - ./docker/frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/www
      - ./app:/www/app
    working_dir: /www/app
    command: nginx -g 'daemon off;'
  php-fpm:
    build:
      context: ./docker/backend/php-fpm
    working_dir: /www/app
    volumes:
      - .:/www
  backend:
    image: nginx:1.21
    ports:
      - "9007:80"
    volumes:
      - ./docker/backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/www
      - ./app:/www/app
    links:
      - php-fpm
    working_dir: /www/app
    command: nginx -g 'daemon off;'